version: '3.8'
services:
  vprodb:
    build:
      context: ./Docker-files/db
    image: luniemma/vprocontainerclouddb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vprocache01: 
    image: memcached
    ports:
      - "11211:11211"

  vprormq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=quest

  vproapp:
    build:
      context: ./Docker-files/app
    image: luniemma/vprocontainercloudapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapp
    
  
  vproweb:
    build:
      context: ./Docker-files/web
    image: luniemma/vprocontainercloudweb
    container_name: vproweb
    ports:
      - "80:80"
volumes:
  vprodbdata: {}
  vproappdata: {}